#!/usr/bin/env python3
import collections
import re
from typing import Set

HANDLED_FIELDS = {
    # core
    'Package',
    'Source',
    'Version',

    # mapped into proper types
    'Priority',
    'Architecture',
    'Format',

    # parsed into Binaries
    'Binaries',

    # parsed into Files
    'Files',

    # parsed build-deps
    'Build-Conflicts',
    'Build-Conflicts-Arch',
    'Build-Conflicts-Indep',
    'Build-Depends',
    'Build-Depends-Arch',
    'Build-Depends-Indep',

    # parsed into VCS
    'Vcs-Arch',
    'Vcs-Browse',
    'Vcs-Browser',
    'Vcs-Bzr',
    'Vcs-Cvs',
    'Vcs-Darcs',
    'Vcs-Git',
    'Vcs-Hg',
    'Vcs-Mtn',
    'Vcs-Svn',

    # folded into Files
    'Checksums-Md5',
    'Checksums-Sha1',
    'Checksums-Sha256',
    'Checksums-Sha512',
}


def to_snake(s: str) -> str:
    return re.sub(r'(?!^)[_-]([a-zA-Z])', lambda m: m.group(1).upper(), s.lower())


def to_rust(s: str) -> str:
    return re.sub(r'[_-]', '_', s.lower())


def main(known_fields: Set[str]):
    text_fields = known_fields - HANDLED_FIELDS
    base_index = 19
    max_len = max(len(to_snake(field)) for field in text_fields)
    capnp_format_string = ('    {: <' + str(max_len) + '} @{} :Text;')
    rust_format_string = '        "{}" => blank_to_null(val, |x| builder.set_{}(x)),\n'

    text_from = collections.defaultdict(set)
    for field in text_fields:
        text_from[to_snake(field)].add(field)

    for i, field in enumerate(sorted(text_from.keys())):
        print(capnp_format_string.format(field, base_index + i))

    with open('src/fields.rs', 'w') as f:
        f.write("""/// GENERATED by gen.py; do not edit

use apt_capnp::source;
use errors::*;
use blank_to_null;

const HANDLED_FIELDS: [&'static str; """ + str(len(HANDLED_FIELDS)) + """] = [
""")
        for field in sorted(HANDLED_FIELDS):
            f.write('    "{}",\n'.format(field))

        f.write("""
];

pub fn set_field(key: &str, val: &str, builder: &mut source::Builder) -> Result<()> {
    if HANDLED_FIELDS.contains(&key) {
        return Ok(());
    }

    match key {
""")
        for orig in sorted(text_fields):
            f.write(rust_format_string.format(orig, to_rust(orig)))
        f.write("""
        other => bail!("unrecognised field: {}", other), 
    }
    
    Ok(())
}
""")


if __name__ == '__main__':
    with open('tagfile-keys.list') as input:
        main(set(line.strip() for line in input.readlines()))
