sudo: false
dist: trusty

language: rust
cache: cargo

rust:
  - nightly
  - beta
  - stable

matrix:
  allow_failures:
    - rust: stable
    - rust: nightly

addons:
  apt:
    packages:
    - libgpg-error-dev
    - libgpgme11-dev
