[package]
authors = ["Chris West (Faux) <git@goeswhere.com>"]
name = "fapt-parse"
version = "0.1.0"

[dependencies]
error-chain = "0.11"
mailparse = "0.6"
md-5 = "0.7"
nom = "4.0.0-beta2"
deb-version = "0.1"

[dependencies.digest]
features = ["std"]
version = "0.7"
