[package]
authors = ["Chris West (Faux) <git@goeswhere.com>"]
name = "fapt-parse"
version = "0.1.0"

[dependencies]
bitflags = "1"
deb-version = "0.1"
failure = "0.1"
mailparse = "0.6"
md-5 = "0.8"
nom = "4"
result = "1"

[dependencies.digest]
features = ["std"]
version = "0.8"
