// GENERATED by gen.py; do not edit
#![cfg_attr(rustfmt, rustfmt_skip)]

use errors::*;
use blank_to_null;

#[cfg(capnp)]
pub fn set_field_source(key: &str, val: &str, builder: &mut unparsed_source::Builder) -> Result<bool> {
    match key {
        "Autobuild" => blank_to_null(val, |x| builder.set_autobuild(x)),
        "Build-Indep-Architecture" => blank_to_null(val, |x| builder.set_build_indep_architecture(x)),
        "Dgit" => blank_to_null(val, |x| builder.set_dgit(x)),
        "Directory" => blank_to_null(val, |x| builder.set_directory(x)),
        "Dm-Upload-Allowed" => blank_to_null(val, |x| builder.set_dm_upload_allowed(x)),
        "Extra-Source-Only" => blank_to_null(val, |x| builder.set_extra_source_only(x)),
        "Go-Import-Path" => blank_to_null(val, |x| builder.set_go_import_path(x)),
        "Homepage" => blank_to_null(val, |x| builder.set_homepage(x)),
        "Python-Version" => blank_to_null(val, |x| builder.set_python_version(x)),
        "Python3-Version" => blank_to_null(val, |x| builder.set_python3_version(x)),
        "Ruby-Versions" => blank_to_null(val, |x| builder.set_ruby_versions(x)),
        "Section" => blank_to_null(val, |x| builder.set_section(x)),
        "Standards-Version" => blank_to_null(val, |x| builder.set_standards_version(x)),
        "Testsuite" => blank_to_null(val, |x| builder.set_testsuite(x)),
        "Testsuite-Restrictions" => blank_to_null(val, |x| builder.set_testsuite_restrictions(x)),
        "Testsuite-Triggers" => blank_to_null(val, |x| builder.set_testsuite_triggers(x)),

        // Typos

        _ => return Ok(false),
    }

    Ok(true)
}

#[cfg(capnp)]
pub fn set_field_binary(key: &str, val: &str, builder: &mut unparsed_binary::Builder) -> Result<bool> {
    match key {
        "Auto-Built-Package" => blank_to_null(val, |x| builder.set_auto_built_package(x)),
        "Bugs" => blank_to_null(val, |x| builder.set_bugs(x)),
        "Build-Ids" => blank_to_null(val, |x| builder.set_build_ids(x)),
        "Built-For-Profiles" => blank_to_null(val, |x| builder.set_built_for_profiles(x)),
        "Built-Using" => blank_to_null(val, |x| builder.set_built_using(x)),
        "Class" => blank_to_null(val, |x| builder.set_class(x)),
        "Conffiles" => blank_to_null(val, |x| builder.set_conffiles(x)),
        "Config-Version" => blank_to_null(val, |x| builder.set_config_version(x)),
        "Files" => blank_to_null(val, |x| builder.set_files(x)),
        "Ghc-Package" => blank_to_null(val, |x| builder.set_ghc_package(x)),
        "Go-Import-Path" => blank_to_null(val, |x| builder.set_go_import_path(x)),
        "Gstreamer-Decoders" => blank_to_null(val, |x| builder.set_gstreamer_decoders(x)),
        "Gstreamer-Elements" => blank_to_null(val, |x| builder.set_gstreamer_elements(x)),
        "Gstreamer-Encoders" => blank_to_null(val, |x| builder.set_gstreamer_encoders(x)),
        "Gstreamer-Uri-Sinks" => blank_to_null(val, |x| builder.set_gstreamer_uri_sinks(x)),
        "Gstreamer-Uri-Sources" => blank_to_null(val, |x| builder.set_gstreamer_uri_sources(x)),
        "Gstreamer-Version" => blank_to_null(val, |x| builder.set_gstreamer_version(x)),
        "Homepage" => blank_to_null(val, |x| builder.set_homepage(x)),
        "Important" => blank_to_null(val, |x| builder.set_important(x)),
        "Installer-Menu-Item" => blank_to_null(val, |x| builder.set_installer_menu_item(x)),
        "Kernel-Version" => blank_to_null(val, |x| builder.set_kernel_version(x)),
        "License" => blank_to_null(val, |x| builder.set_license(x)),
        "Lua-Versions" => blank_to_null(val, |x| builder.set_lua_versions(x)),
        "MSDOS-Filename" => blank_to_null(val, |x| builder.set_msdos_filename(x)),
        "Modaliases" => blank_to_null(val, |x| builder.set_modaliases(x)),
        "Multi-Arch" => blank_to_null(val, |x| builder.set_multi_arch(x)),
        "Npp-Applications" => blank_to_null(val, |x| builder.set_npp_applications(x)),
        "Npp-Description" => blank_to_null(val, |x| builder.set_npp_description(x)),
        "Npp-File" => blank_to_null(val, |x| builder.set_npp_file(x)),
        "Npp-Mimetype" => blank_to_null(val, |x| builder.set_npp_mimetype(x)),
        "Npp-Name" => blank_to_null(val, |x| builder.set_npp_name(x)),
        "Optional" => blank_to_null(val, |x| builder.set_optional(x)),
        "Origin" => blank_to_null(val, |x| builder.set_origin(x)),
        "Package-Revision" => blank_to_null(val, |x| builder.set_package_revision(x)),
        "Package-Type" => blank_to_null(val, |x| builder.set_package_type(x)),
        "Phased-Update-Percentage" => blank_to_null(val, |x| builder.set_phased_update_percentage(x)),
        "Postgresql-Catversion" => blank_to_null(val, |x| builder.set_postgresql_catversion(x)),
        "Postgresql-Version" => blank_to_null(val, |x| builder.set_postgresql_version(x)),
        "Python-Egg-Name" => blank_to_null(val, |x| builder.set_python_egg_name(x)),
        "Python-Version" => blank_to_null(val, |x| builder.set_python_version(x)),
        "Python3-Version" => blank_to_null(val, |x| builder.set_python3_version(x)),
        "Recommended" => blank_to_null(val, |x| builder.set_recommended(x)),
        "Revision" => blank_to_null(val, |x| builder.set_revision(x)),
        "Ruby-Versions" => blank_to_null(val, |x| builder.set_ruby_versions(x)),
        "Section" => blank_to_null(val, |x| builder.set_section(x)),
        "Source" => blank_to_null(val, |x| builder.set_source(x)),
        "Status" => blank_to_null(val, |x| builder.set_status(x)),
        "Subarchitecture" => blank_to_null(val, |x| builder.set_subarchitecture(x)),
        "Supported" => blank_to_null(val, |x| builder.set_supported(x)),
        "Tads2-Version" => blank_to_null(val, |x| builder.set_tads2_version(x)),
        "Tads3-Version" => blank_to_null(val, |x| builder.set_tads3_version(x)),
        "Tag" => blank_to_null(val, |x| builder.set_tag(x)),
        "Task" => blank_to_null(val, |x| builder.set_task(x)),
        "Triggers-Awaited" => blank_to_null(val, |x| builder.set_triggers_awaited(x)),
        "Triggers-Pending" => blank_to_null(val, |x| builder.set_triggers_pending(x)),
        "Vendor" => blank_to_null(val, |x| builder.set_vendor(x)),
        "Xul-Appid" => blank_to_null(val, |x| builder.set_xul_appid(x)),

        // Typos
        "Package_Revision" => blank_to_null(val, |x| builder.set_package_revision(x)),

        _ => return Ok(false),
    }

    Ok(true)
}
