[package]
authors = ["Chris West (Faux) <git@goeswhere.com>"]
name = "fapt-pkg"
version = "0.1.0"

[dependencies]
error-chain = "0.11"
flate2 = "0.2"
gpgme = "0.6"
hex = "0.2"
mailparse = "0.6"
md-5 = "0.5"
nom = "3.2"
reqwest = "0.8"
serde_json = "1.0"
sha2 = "0.6"
tempdir = "0.3"
tempfile-fast = "0.1"

[dependencies.digest]
features = ["std"]
version = "0.6"
