[package]
authors = ["Chris West (Faux) <git@goeswhere.com>"]
name = "fapt-pkg"
version = "0.1.0"

[dependencies]
error-chain = "0.11"
gpgme = "0.6"
hex = "0.2"
inflate = "0.3"
mailparse = "0.6"
nom = "3.2"
reqwest = "0.8"
tempdir = "0.3"
tempfile-fast = "0.1"
